import{backupBeforeImport,budgetCategories,clearData,createEmptyData,loadData,normalizeData,saveData,validateImport}from'./storage.js';
import{buildInsights,calcSummary,createDemoData,healthLabel,money,months,percent,selectedTransactions,today,uid}from'./finance.js';
import{drawBarChart,drawDonutChart,drawHorizontalBars}from'./charts.js';
import{budgetCard,byId,debtItem,emptyState,fillTransactionCategories,insightItem,investmentItem,renderKpis,setText,setupMonthYear,transactionItem}from'./ui.js';
let data=loadData();let lastViewportWidth=window.innerWidth;const now=new Date();const state={page:'dashboard',month:now.getMonth()+1,year:now.getFullYear(),search:''};
function saveAndRender(){saveData(data);render()}
function initialize(){document.documentElement.dataset.theme=data.settings.theme||'light';byId('themeBtn').textContent=data.settings.theme==='dark'?'الوضع النهاري':'الوضع الليلي';setupMonthYear(byId('monthFilter'),byId('yearFilter'),state,render);bindEvents();fillTransactionCategories(byId('txType'),byId('txCategory'));updateOnboarding();render();registerServiceWorkerIfAvailable()}function registerServiceWorkerIfAvailable(){const protocol=window.location.protocol;const canRegister='serviceWorker'in navigator&&(protocol==='http:'||protocol==='https:');if(!canRegister)return;navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
function updateOnboarding(){byId('onboarding').classList.toggle('is-hidden',data.initialized);byId('mainApp').classList.toggle('is-hidden',!data.initialized);const controlStrip=document.querySelector('.control-strip');const bottomNav=document.querySelector('.bottom-nav');if(controlStrip)controlStrip.classList.toggle('is-hidden',!data.initialized);if(bottomNav)bottomNav.classList.toggle('is-hidden',!data.initialized)}
function render(){if(!data.initialized)return;renderDashboard();renderTransactions();renderBudget();renderDebts();renderInvestments();renderAnalytics()}
function renderDashboard(){const s=calcSummary(data,state);setText('periodLabel',`${months[state.month-1]} ${state.year}`);setText('sumIncome',money(s.income));setText('sumExpenses',money(s.expenses));setText('sumNet',money(s.net));setText('savingRate',`${percent(s.savingRate)} ادخار`);setText('incomeCount',`${s.transactions.filter(i=>i.type==='income').length} مصدر`);setText('expenseCount',`${s.transactions.filter(i=>i.type==='expense').length} عملية`);setText('healthScore',`${s.healthScore}/100`);setText('healthLabel',healthLabel(s.healthScore));const net=byId('sumNet');net.classList.toggle('positive',s.net>=0);net.classList.toggle('negative',s.net<0);byId('recentList').innerHTML=s.transactions.slice(0,6).map(transactionItem).join('')||emptyState('لا توجد معاملات لهذا الشهر.');byId('insights').innerHTML=buildInsights(s).map(insightItem).join('');drawDonutChart(byId('donutCanvas'),[{label:'مصروفات',value:s.expenses,color:css('--negative')},{label:'صافي',value:Math.max(0,s.net),color:css('--positive')},{label:'ديون',value:s.debtRemaining,color:css('--warning')},{label:'استثمار',value:s.investmentCapital,color:css('--brand')}]);bindItemClickHandlers()}
function renderTransactions(){const q=state.search.trim().toLowerCase();const tx=selectedTransactions(data,state).filter(i=>!q||[i.name,i.category,i.notes,i.type].join(' ').toLowerCase().includes(q));byId('transactionList').innerHTML=tx.map(transactionItem).join('')||emptyState('لا توجد معاملات مطابقة.');bindItemClickHandlers()}
function renderBudget(){const tx=selectedTransactions(data,state).filter(i=>i.type==='expense');const spent={};tx.forEach(i=>spent[i.category]=(spent[i.category]||0)+Number(i.amount||0));byId('budgetList').innerHTML=budgetCategories.map(c=>budgetCard(c,Number(data.budgets[c]||0),Number(spent[c]||0))).join('');document.querySelectorAll('.budget-input').forEach(input=>{input.addEventListener('change',()=>{data.budgets[input.dataset.budget]=Number(input.value||0);saveAndRender()})})}
function renderDebts(){const total=data.debts.reduce((s,d)=>s+Math.max(0,Number(d.amount||0)-Number(d.paid||0)),0);const overdue=data.debts.filter(d=>d.dueDate&&new Date(d.dueDate)<new Date(today())&&Math.max(0,Number(d.amount||0)-Number(d.paid||0))>0).length;setText('sumDebts',money(total));setText('debtCount',`${data.debts.length} دين`);setText('overdueDebts',String(overdue));byId('debtList').innerHTML=data.debts.map(debtItem).join('')||emptyState('لا توجد ديون.');bindItemClickHandlers()}
function renderInvestments(){const capital=data.investments.reduce((s,i)=>s+Number(i.capital||0),0);const profit=data.investments.reduce((s,i)=>s+Number(i.profit||0),0);const roi=capital>0?profit/capital*100:0;setText('sumCapital',money(capital));setText('sumProfit',money(profit));setText('investmentCount',`${data.investments.length} استثمار`);setText('roiLabel',`${percent(roi)} عائد`);const el=byId('sumProfit');el.classList.toggle('positive',profit>=0);el.classList.toggle('negative',profit<0);byId('investmentList').innerHTML=data.investments.map(investmentItem).join('')||emptyState('لا توجد استثمارات.');bindItemClickHandlers()}
function renderAnalytics(){const s=calcSummary(data,state);renderKpis(byId('analyticsKpis'),s);drawBarChart(byId('incomeExpenseCanvas'),[{label:'دخل',value:s.income,color:css('--positive')},{label:'مصروف',value:s.expenses,color:css('--negative')},{label:'صافي',value:Math.max(0,s.net),color:css('--brand')}]);const days=new Date(state.year,state.month,0).getDate();const daily=Array.from({length:days},(_,i)=>({label:i+1,value:s.dailySpend[i+1]||0,color:css('--brand')}));drawBarChart(byId('dailyExpenseCanvas'),daily,{height:270});const budgetUsageItems=budgetCategories.map(c=>{const b=Number(data.budgets[c]||0);const spent=Number(s.categorySpend[c]||0);const usage=b>0?Math.min(100,spent/b*100):0;return{label:c,value:usage,color:usage>=100?css('--negative'):usage>=80?css('--warning'):css('--positive')}}).sort((a,b)=>b.value-a.value);drawHorizontalBars(byId('budgetUsageCanvas'),budgetUsageItems);const total=Object.values(s.categorySpend).reduce((a,b)=>a+b,0);byId('categoryBreakdown').innerHTML=s.categoryEntries.map(([c,v])=>{const share=total>0?v/total*100:0;return`<article class="list-item"><div><div class="item-title">${c}</div><div class="item-meta">${percent(share)} من إجمالي المصروفات</div></div><strong class="item-amount danger-text">${money(v)}</strong></article>`}).join('')||emptyState('لا توجد مصروفات لتحليلها.');byId('analyticsInsights').innerHTML=buildInsights(s).map(insightItem).join('')}
function bindEvents(){document.querySelector('.bottom-nav').addEventListener('click',e=>{const btn=e.target.closest('[data-page]');if(btn)goToPage(btn.dataset.page)});document.body.addEventListener('click',e=>{const btn=e.target.closest('[data-go]');if(btn)goToPage(btn.dataset.go)});byId('startEmptyBtn').addEventListener('click',()=>{data.initialized=true;saveAndRender();updateOnboarding()});byId('loadDemoBtn').addEventListener('click',()=>{data=createDemoData(createEmptyData);saveAndRender();updateOnboarding()});byId('themeBtn').addEventListener('click',toggleTheme);byId('printBtn').addEventListener('click',()=>window.print());byId('exportBtn').addEventListener('click',exportData);byId('exportBtn2').addEventListener('click',exportData);byId('importBtn').addEventListener('click',()=>byId('importFile').click());byId('importBtn2').addEventListener('click',()=>byId('importFile').click());byId('importFile').addEventListener('change',importData);byId('clearBtn').addEventListener('click',()=>{if(!confirm('سيتم مسح كل بيانات CashPilot من هذا المتصفح. هل أنت متأكد؟'))return;clearData();data=createEmptyData();updateOnboarding();saveAndRender()});byId('addTransactionBtn').addEventListener('click',()=>openTransactionModal());byId('addTransactionBtn2').addEventListener('click',()=>openTransactionModal());byId('addDebtBtn').addEventListener('click',()=>openDebtModal());byId('addInvestmentBtn').addEventListener('click',()=>openInvestmentModal());byId('searchInput').addEventListener('input',e=>{state.search=e.target.value;renderTransactions()});byId('txType').addEventListener('change',()=>fillTransactionCategories(byId('txType'),byId('txCategory')));byId('transactionForm').addEventListener('submit',saveTransaction);byId('debtForm').addEventListener('submit',saveDebt);byId('investmentForm').addEventListener('submit',saveInvestment);byId('deleteTransactionBtn').addEventListener('click',deleteTransaction);byId('deleteDebtBtn').addEventListener('click',deleteDebt);byId('deleteInvestmentBtn').addEventListener('click',deleteInvestment);document.querySelectorAll('[data-close]').forEach(btn=>btn.addEventListener('click',()=>btn.closest('dialog').close()));window.addEventListener('resize',handleViewportResize)}function handleViewportResize(){const currentWidth=window.innerWidth;if(currentWidth===lastViewportWidth)return;lastViewportWidth=currentWidth;render()}
function goToPage(page){state.page=page;document.querySelectorAll('.page').forEach(section=>section.classList.toggle('active-page',section.id===`page-${page}`));document.querySelectorAll('.nav-tab').forEach(tab=>tab.classList.toggle('active-tab',tab.dataset.page===page));render()}
function bindItemClickHandlers(){document.querySelectorAll('[data-edit-transaction]').forEach(el=>el.onclick=()=>openTransactionModal(el.dataset.editTransaction));document.querySelectorAll('[data-edit-debt]').forEach(el=>el.onclick=()=>openDebtModal(el.dataset.editDebt));document.querySelectorAll('[data-edit-investment]').forEach(el=>el.onclick=()=>openInvestmentModal(el.dataset.editInvestment))}
function openTransactionModal(id=null){const item=id?data.transactions.find(e=>e.id===id):null;byId('txId').value=item?.id||'';byId('txType').value=item?.type||'expense';fillTransactionCategories(byId('txType'),byId('txCategory'),item?.category);byId('txDate').value=item?.date||today();byId('txName').value=item?.name||'';byId('txAmount').value=item?.amount||'';byId('txNotes').value=item?.notes||'';byId('deleteTransactionBtn').classList.toggle('is-hidden',!item);byId('transactionModal').showModal()}
function openDebtModal(id=null){const d=id?data.debts.find(e=>e.id===id):null;byId('debtId').value=d?.id||'';byId('debtName').value=d?.name||'';byId('debtAmount').value=d?.amount||'';byId('debtPaid').value=d?.paid||0;byId('debtDue').value=d?.dueDate||'';byId('debtNotes').value=d?.notes||'';byId('deleteDebtBtn').classList.toggle('is-hidden',!d);byId('debtModal').showModal()}
function openInvestmentModal(id=null){const i=id?data.investments.find(e=>e.id===id):null;byId('investmentId').value=i?.id||'';byId('investmentName').value=i?.name||'';byId('investmentType').value=i?.type||'أخرى';byId('investmentStart').value=i?.startDate||today();byId('investmentCapital').value=i?.capital||'';byId('investmentProfit').value=i?.profit||0;byId('deleteInvestmentBtn').classList.toggle('is-hidden',!i);byId('investmentModal').showModal()}
function saveTransaction(e){e.preventDefault();const item={id:byId('txId').value||uid(),type:byId('txType').value,date:byId('txDate').value,name:byId('txName').value.trim(),amount:Number(byId('txAmount').value),category:byId('txCategory').value,notes:byId('txNotes').value.trim()};if(!item.name||item.amount<=0||!item.date)return alert('أدخل بيانات معاملة صحيحة.');const idx=data.transactions.findIndex(e=>e.id===item.id);if(idx>=0)data.transactions[idx]=item;else data.transactions.push(item);byId('transactionModal').close();saveAndRender()}
function saveDebt(e){e.preventDefault();const item={id:byId('debtId').value||uid(),name:byId('debtName').value.trim(),amount:Number(byId('debtAmount').value),paid:Number(byId('debtPaid').value||0),dueDate:byId('debtDue').value,notes:byId('debtNotes').value.trim()};if(!item.name||item.amount<=0)return alert('أدخل بيانات دين صحيحة.');const idx=data.debts.findIndex(e=>e.id===item.id);if(idx>=0)data.debts[idx]=item;else data.debts.push(item);byId('debtModal').close();saveAndRender()}
function saveInvestment(e){e.preventDefault();const item={id:byId('investmentId').value||uid(),name:byId('investmentName').value.trim(),type:byId('investmentType').value,startDate:byId('investmentStart').value,capital:Number(byId('investmentCapital').value),profit:Number(byId('investmentProfit').value||0)};if(!item.name||item.capital<=0)return alert('أدخل بيانات استثمار صحيحة.');const idx=data.investments.findIndex(e=>e.id===item.id);if(idx>=0)data.investments[idx]=item;else data.investments.push(item);byId('investmentModal').close();saveAndRender()}
function deleteTransaction(){const id=byId('txId').value;if(!id||!confirm('حذف هذه المعاملة؟'))return;data.transactions=data.transactions.filter(i=>i.id!==id);byId('transactionModal').close();saveAndRender()}
function deleteDebt(){const id=byId('debtId').value;if(!id||!confirm('حذف هذا الدين؟'))return;data.debts=data.debts.filter(i=>i.id!==id);byId('debtModal').close();saveAndRender()}
function deleteInvestment(){const id=byId('investmentId').value;if(!id||!confirm('حذف هذا الاستثمار؟'))return;data.investments=data.investments.filter(i=>i.id!==id);byId('investmentModal').close();saveAndRender()}
function toggleTheme(){data.settings.theme=data.settings.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=data.settings.theme;byId('themeBtn').textContent=data.settings.theme==='dark'?'الوضع النهاري':'الوضع الليلي';saveAndRender()}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`cashpilot-backup-${today()}.json`;link.click();URL.revokeObjectURL(url)}
function importData(event){const file=event.target.files[0];event.target.value='';if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const payload=JSON.parse(reader.result);const error=validateImport(payload);if(error)return alert(error);backupBeforeImport(data);data=normalizeData(payload);data.initialized=true;saveAndRender();updateOnboarding();alert('تم الاستيراد بنجاح. تم حفظ نسخة احتياطية قبل الاستيراد.')}catch{alert('فشل قراءة ملف JSON.')}};reader.readAsText(file)}
function css(name){return getComputedStyle(document.documentElement).getPropertyValue(name).trim()}
document.addEventListener('DOMContentLoaded',initialize);
