export const months=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
export const categories={income:['راتب','عمل حر','مشاريع','استثمار','أخرى'],expense:['طعام','مواصلات','دراسة','صحة','فواتير','إنترنت','تسوق','ترفيه','أخرى']};
export function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
export function formatLocalDate(date=new Date()){const y=date.getFullYear();const m=String(date.getMonth()+1).padStart(2,'0');const d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}export function today(){return formatLocalDate(new Date())}
export function money(v){return(Number(v)||0).toLocaleString('ar-EG',{maximumFractionDigits:0})+' ج.م'}
export function percent(v){return(Number(v)||0).toFixed(1)+'%'}
export function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
export function parseSafeDate(v){const d=new Date(v);return Number.isNaN(d.getTime())?null:d}
export function samePeriod(item,state){const d=parseSafeDate(item.date||item.dueDate||item.startDate);return Boolean(d)&&d.getMonth()+1===Number(state.month)&&d.getFullYear()===Number(state.year)}
export function selectedTransactions(data,state){return data.transactions.filter(i=>samePeriod(i,state)).sort((a,b)=>new Date(b.date)-new Date(a.date))}
export function calcSummary(data,state){const transactions=selectedTransactions(data,state);const income=transactions.filter(i=>i.type==='income').reduce((s,i)=>s+Number(i.amount||0),0);const expenses=transactions.filter(i=>i.type==='expense').reduce((s,i)=>s+Number(i.amount||0),0);const net=income-expenses;const savingRate=income>0?net/income*100:0;const spendRate=income>0?expenses/income*100:0;const debtRemaining=data.debts.reduce((s,d)=>s+Math.max(0,Number(d.amount||0)-Number(d.paid||0)),0);const investmentCapital=data.investments.reduce((s,i)=>s+Number(i.capital||0),0);const investmentProfit=data.investments.reduce((s,i)=>s+Number(i.profit||0),0);const roi=investmentCapital>0?investmentProfit/investmentCapital*100:0;const categorySpend={};const dailySpend={};let largestTransaction=null;transactions.filter(i=>i.type==='expense').forEach(i=>{const amount=Number(i.amount||0);categorySpend[i.category]=(categorySpend[i.category]||0)+amount;const d=parseSafeDate(i.date);if(d){const day=d.getDate();dailySpend[day]=(dailySpend[day]||0)+amount}if(!largestTransaction||amount>Number(largestTransaction.amount||0))largestTransaction=i});const categoryEntries=Object.entries(categorySpend).sort((a,b)=>b[1]-a[1]);const topCategory=categoryEntries[0]||null;const daysInMonth=new Date(state.year,state.month,0).getDate();const current=new Date();const elapsed=state.month===current.getMonth()+1&&state.year===current.getFullYear()?current.getDate():daysInMonth;const avgDailySpend=elapsed>0?expenses/elapsed:0;const projectedMonthEnd=income-avgDailySpend*daysInMonth;const debtToIncome=income>0?debtRemaining/income*100:0;const budgetTotal=Object.values(data.budgets).reduce((s,v)=>s+Number(v||0),0);const budgetUsage=budgetTotal>0?expenses/budgetTotal*100:0;const healthScore=calcHealthScore({income,expenses,savingRate,debtRemaining});return{transactions,income,expenses,net,savingRate,spendRate,debtRemaining,investmentCapital,investmentProfit,roi,categorySpend,categoryEntries,dailySpend,topCategory,largestTransaction,avgDailySpend,projectedMonthEnd,debtToIncome,budgetTotal,budgetUsage,healthScore}}
function calcHealthScore(s){if(s.income<=0)return 0;let score=52;score+=Math.min(28,Math.max(-30,s.savingRate));score-=Math.min(28,(s.debtRemaining/Math.max(s.income,1))*9);if(s.expenses>s.income)score-=18;if(s.savingRate>=20)score+=6;return Math.max(0,Math.min(100,Math.round(score)))}
export function healthLabel(score){if(score>=82)return'ممتاز';if(score>=66)return'جيد';if(score>=48)return'متوسط';if(score>0)return'خطر';return'غير محدد'}
export function buildInsights(summary){const out=[];if(summary.income<=0)out.push('لا يوجد دخل مسجل لهذا الشهر؛ التحليل سيكون محدودًا.');if(summary.income>0&&summary.spendRate>=90)out.push('معدل الإنفاق مرتفع جدًا مقارنة بالدخل، راجع الفئات الأعلى ضغطًا.');if(summary.budgetTotal>0&&summary.budgetUsage>=100)out.push('تم تجاوز الميزانية الشهرية المحددة.');else if(summary.budgetTotal>0&&summary.budgetUsage>=80)out.push('استهلاك الميزانية اقترب من الحد الأعلى.');if(summary.debtToIncome>=200)out.push('الديون المتبقية مرتفعة جدًا مقارنة بالدخل الشهري.');if(summary.savingRate>=20)out.push('معدل الادخار جيد لهذا الشهر.');if(summary.topCategory)out.push(`أعلى فئة إنفاق هي ${summary.topCategory[0]} بقيمة ${money(summary.topCategory[1])}.`);if(!out.length)out.push('الوضع المالي مستقر نسبيًا في الفترة المحددة.');return out}
export function createDemoData(baseFactory){const data=baseFactory();const now=new Date();const y=now.getFullYear();const m=String(now.getMonth()+1).padStart(2,'0');const date=d=>`${y}-${m}-${String(d).padStart(2,'0')}`;data.initialized=true;data.transactions=[{id:uid(),type:'income',name:'راتب شهري',amount:12000,category:'راتب',date:date(1),notes:''},{id:uid(),type:'income',name:'مشروع حر',amount:2500,category:'عمل حر',date:date(8),notes:''},{id:uid(),type:'expense',name:'سوبر ماركت',amount:850,category:'طعام',date:date(2),notes:''},{id:uid(),type:'expense',name:'مواصلات',amount:300,category:'مواصلات',date:date(3),notes:''},{id:uid(),type:'expense',name:'إنترنت',amount:240,category:'إنترنت',date:date(6),notes:''},{id:uid(),type:'expense',name:'دراسة',amount:900,category:'دراسة',date:date(8),notes:''},{id:uid(),type:'expense',name:'فواتير',amount:650,category:'فواتير',date:date(10),notes:''}];data.budgets={...data.budgets,'طعام':2000,'مواصلات':800,'دراسة':1500,'إنترنت':450,'فواتير':900};const nextMonth=formatLocalDate(new Date(y,now.getMonth()+1,15));data.debts=[{id:uid(),name:'قرض شخصي',amount:25000,paid:9000,dueDate:nextMonth,notes:'قسط شهري'}];data.investments=[{id:uid(),name:'ذهب',type:'ذهب',capital:10000,profit:2800,startDate:`${y-1}-06-01`}];return data}
