import { t } from '../core/i18n.js';
import{budgetCategories}from'./storage.js';import{categories,escapeHtml,money,months,percent}from'./finance.js';
export function byId(id){return document.getElementById(id)}
export function setText(id,value){const el=byId(id);if(el)el.textContent=value}
export function emptyState(msg){return`<div class="empty-state">${escapeHtml(msg)}</div>`}
export function transactionItem(t){const isIncome=t.type==='income';const sign=isIncome?'+':'−';const cls=isIncome?'positive-text':'danger-text';return`<article class="list-item clickable" data-edit-transaction="${escapeHtml(t.id)}"><div><div class="item-title">${escapeHtml(t.name)}</div><div class="item-meta">${escapeHtml(t.category)} · ${escapeHtml(t.date)}${t.notes?' · '+escapeHtml(t.notes):''}</div></div><strong class="item-amount ${cls}">${sign}${money(t.amount)}</strong></article>`}
export function debtItem(d){const amount=Number(d.amount||0),paid=Number(d.paid||0),remaining=Math.max(0,amount-paid),paidRatio=amount>0?paid/amount*100:0;return`<article class="list-item clickable" data-edit-debt="${escapeHtml(d.id)}"><div><div class="item-title">${escapeHtml(d.name)}</div><div class="item-meta">المتبقي ${money(remaining)} · السداد ${percent(paidRatio)}${d.dueDate?' · الاستحقاق '+escapeHtml(d.dueDate):''}</div></div><strong class="item-amount danger-text">${money(remaining)}</strong></article>`}
export function investmentItem(i){const capital=Number(i.capital||0),profit=Number(i.profit||0),roi=capital>0?profit/capital*100:0;return`<article class="list-item clickable" data-edit-investment="${escapeHtml(i.id)}"><div><div class="item-title">${escapeHtml(i.name)}</div><div class="item-meta">${escapeHtml(i.type)} · رأس المال ${money(capital)} · العائد ${percent(roi)}</div></div><strong class="item-amount ${profit>=0?'positive-text':'danger-text'}">${money(profit)}</strong></article>`}
export function budgetCard(category,budgeted,spent){const pct=budgeted>0?Math.min(100,spent/budgeted*100):0;const status=pct>=100?'danger':pct>=80?'warning':'';return`<article class="budget-card"><div class="item-title">${escapeHtml(category)}</div><div class="item-meta">${money(spent)} مصروف من ${budgeted?money(budgeted):'ميزانية غير محددة'}</div><div class="progress-track"><div class="progress-fill ${status}" style="width:${pct}%"></div></div><input class="control ltr-input budget-input" data-budget="${escapeHtml(category)}" type="number" min="0" step="50" value="${budgeted||''}" placeholder="حدد ميزانية ${escapeHtml(category)}"></article>`}
export function insightItem(message){return`<div class="insight">${escapeHtml(message)}</div>`}
export function renderKpis(container,summary){const items=[[t('stat_net'),money(summary.net)],['متوسط الإنفاق اليومي',money(summary.avgDailySpend)],['متوقع نهاية الشهر',money(summary.projectedMonthEnd)],['استهلاك الميزانية',percent(summary.budgetUsage)],['الدين إلى الدخل',percent(summary.debtToIncome)],['ROI الاستثمارات',percent(summary.roi)],['الصحة المالية',`${summary.healthScore}/100`],['أكبر مصروف',summary.largestTransaction?money(summary.largestTransaction.amount):'—']];container.innerHTML=items.map(([label,value])=>`<article class="analytics-kpi"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></article>`).join('')}
export function setupMonthYear(monthSelect,yearSelect,state,onChange){monthSelect.innerHTML=months.map((m,i)=>`<option value="${i+1}">${m}</option>`).join('');const y=new Date().getFullYear();yearSelect.innerHTML=Array.from({length:7},(_,i)=>y+1-i).map(year=>`<option value="${year}">${year}</option>`).join('');monthSelect.value=state.month;yearSelect.value=state.year;monthSelect.addEventListener('change',()=>{state.month=Number(monthSelect.value);onChange()});yearSelect.addEventListener('change',()=>{state.year=Number(yearSelect.value);onChange()})}
export function fillTransactionCategories(typeSelect,categorySelect,selected=null){const list=categories[typeSelect.value]||categories.expense;categorySelect.innerHTML=list.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join('');categorySelect.value=selected||list[0]}
export{budgetCategories};
